AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.1

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Lint/ItWithoutArgumentsInBlock:
  Enabled: false

Layout/LineLength:
  Max: 160

Metrics/MethodLength:
  Max: 15

Metrics/ClassLength:
  Max: 120
