module Cosmo
  class Config
    NANO: Integer
    DEFAULT_PATH: ::String

    self.@instance: Config
    self.@system: Hash[Symbol, untyped]
    @config: Hash[Symbol, untyped]?
    @system: Hash[Symbol, untyped]
    @defaults: Hash[Symbol, untyped]

    def self.instance: () -> Config

    def self.system: () -> Hash[Symbol, untyped]

    def self.parse_file: (::String path) -> Hash[Symbol, untyped]

    def self.normalize!: (Hash[Symbol, untyped] config) -> void

    def self.deliver_policy: (Symbol | ::String | Time start_position) -> Hash[Symbol, ::String]

    def self.[]: (Symbol key) -> untyped

    def self.fetch: (Symbol key, ?untyped default) -> untyped

    def self.dig: (*Symbol keys) -> untyped

    def self.to_h: () -> Hash[Symbol, untyped]

    def self.set: (*untyped) -> untyped

    def self.load: (?::String? path) -> void

    def initialize: () -> void

    def []: (Symbol key) -> untyped

    def fetch: (Symbol key, ?untyped default) -> untyped

    def dig: (*Symbol keys) -> untyped

    def to_h: () -> Hash[Symbol, untyped]

    def set: (*untyped) -> untyped

    def load: (?::String? path) -> void
  end
end
