module Cosmo
  module Job
    def self.included: (Class base) -> void

    module ClassMethods
      @default_options: Hash[Symbol, untyped]

      def options: (?stream: Symbol?, ?retry: Integer?, ?dead: bool?) -> Hash[Symbol, untyped]

      def perform: (*untyped args, ?async: bool, **untyped options) -> (::String | nil)

      def perform_async: (*untyped args) -> ::String

      def perform_at: (Integer | Time timestamp, *untyped args) -> ::String

      def perform_in: (Integer | Float interval, *untyped args) -> ::String

      def perform_sync: (*untyped args) -> void

      def default_options: () -> Hash[Symbol, untyped]

      private

      def client: () -> Client
    end

    attr_reader jid: ::String

    def jid=: (::String) -> ::String

    def perform: (*untyped) -> untyped

    def logger: () -> untyped
  end
end
