module Cosmo
  module Stream
    class Message
      @msg: untyped
      @serializer: Module

      def initialize: (untyped msg, ?serializer: Module?) -> void

      def subject: () -> ::String

      def reply: () -> ::String?

      def header: () -> Hash[::String, untyped]

      def ack: () -> void

      def nack: (?delay: Integer?) -> void

      def term: () -> void

      def data: () -> untyped
    end
  end
end
