module Cosmo
  module Utils
    module Hash
      def self.symbolize_keys!: (untyped obj) -> (::Hash[Symbol, untyped] | Array[untyped] | untyped)

      def self.dup: [T] (T hash) -> T

      def self.keys?: (::Hash[untyped, untyped] hash, *untyped keys) -> bool

      def self.set: (::Hash[untyped, untyped] hash, *untyped keys, value: untyped) -> untyped

      def self.merge: (::Hash[untyped, untyped] hash1, ::Hash[untyped, untyped]? hash2) -> ::Hash[untyped, untyped]

      def symbolize_keys!: (untyped obj) -> (::Hash[Symbol, untyped] | Array[untyped] | untyped)

      def dup: [T] (T hash) -> T

      def keys?: (::Hash[untyped, untyped] hash, *untyped keys) -> bool

      def set: (::Hash[untyped, untyped] hash, *untyped keys, value: untyped) -> untyped

      def merge: (::Hash[untyped, untyped] hash1, ::Hash[untyped, untyped]? hash2) -> ::Hash[untyped, untyped]
    end
  end
end
