module Cosmo
  module Utils
    module String
      def self.underscore: (::String | Symbol value) -> ::String

      def self.safe_constantize: (::String value) -> Class?

      def underscore: (::String | Symbol value) -> ::String

      def safe_constantize: (::String value) -> Class?
    end
  end
end
